### ISSUE TITLE
No variables and methods are generated after the code is reversed in Windows10

### ISSUE THREAD

**Issue by LiuShuangFrost** [staruml/staruml-java#18]

**Comment by crisrivlop** [comment]
Also this happen in Windows 7

**Comment by crisrivlop** [comment]
Hello i have the solution (almost tested for linux) at method `translateMembers (options, namespace, memberNodeArray)` at file "code-analizer.js" at line 692 the if sentence 
`if ((typeof memberNode === 'string') && memberNode.node)`
should be replace by:
`if ((typeof memberNode.node === 'string') && memberNode.node)`
obviouly memberNode is not a string typed variable. Also you need to try if the node value (it contains the token name) is a string and not his owner object. If you dont understand me, please contact me,

**Comment by niklauslee** [comment]
Thank you for informing. Now it is fixed.
